// =============================================================================
// CUSTOMER CHURN FEATURE EXTRACTION QUERY
// =============================================================================
//
// PURPOSE
// Extracts monthly customer snapshots with behavioral features for churn
// prediction modeling. Each row represents one customer at one point in time.
//
// CUSTOMER SCOPE
// - Cost Centers: CMFIT, CMSCH, GAME (excluding GAMENESSR)
// - Excludes customers marked as DEAD segment
// - Includes all "alive" customers (ordered within 365 days of snapshot)
// - Customers appear in every month they're alive, even without orders
//
// TIME PERIODS
// - CY (Current Year): 365 days prior to snapshot
// - PY (Prior Year): 366-730 days prior to snapshot
// - Lifetime: All time up to snapshot
//
// OUTPUT FEATURES (72 columns)
//
// Identifiers:
//   - CustomerId, AccountName, Segment, CostCenter
//   - SnapshotDate, FirstPurchaseDate, LastPurchaseDate
//
// Aggregate Metrics:
//   - Orders_CY, Orders_PY, Orders_Lifetime
//   - Spend_CY, Spend_PY, Spend_Lifetime
//   - Units_CY, Units_PY, Units_Lifetime
//   - AOV_CY, DaysSinceLast, TenureDays
//
// Trend Metrics:
//   - Spend_Trend (CY/PY ratio)
//   - Orders_Trend (CY/PY ratio)
//   - Units_Trend (CY/PY ratio)
//
// CUBS Category Metrics (per category: Uniforms, Sparring, Belts, Bags, Customs):
//   - {Category}_Units_CY, {Category}_Units_PY, {Category}_Units_Lifetime
//   - {Category}_Spend_CY, {Category}_Spend_PY, {Category}_Spend_Lifetime
//   - {Category}_Orders_CY, {Category}_Orders_Lifetime
//   - {Category}_DaysSinceLast, {Category}_Pct_of_Total_CY
//
// Breadth Metrics:
//   - CUBS_Categories_Active_CY (0-5)
//   - CUBS_Categories_Active_PY (0-5)
//   - CUBS_Categories_Ever (0-5)
//   - CUBS_Categories_Trend (CY - PY)
//
// USAGE
// Production: Automatically uses prior month's end date (runs on 1st of each month).
// For arbitrary months, use the other DAX file.
// Export to CSV, combine months into train.csv and validate.csv for modeling.
//
// =============================================================================

EVALUATE
VAR SnapshotDate = EOMONTH(TODAY(), -1)  // Automatically uses prior month's end date

VAR CustomerBase =
    FILTER(
        Customers,
        Customers[Cost Center] IN {"CMFIT", "CMSCH", "GAME"}
        && NOT (Customers[Cost Center] = "GAME" && Customers[CustomerGroup] = "GAMENESSR")
        && Customers[Segment] <> "DEAD"
        && NOT ISBLANK(Customers[FirstOrdered])
        && Customers[FirstOrdered] <= SnapshotDate
        && CALCULATE(
            MAX(Sales[date_Invoice]),
            Sales[date_Invoice] <= SnapshotDate
        ) >= SnapshotDate - 365
    )

RETURN
ADDCOLUMNS(
    CustomerBase,

    // === IDENTIFIERS ===
    "SnapshotDate", FORMAT(SnapshotDate, "YYYY-MM-DD"),
    "FirstPurchaseDate", FORMAT(Customers[FirstOrdered], "YYYY-MM-DD"),
    "LastPurchaseDate",
        FORMAT(
            CALCULATE(MAX(Sales[date_Invoice]), Sales[date_Invoice] <= SnapshotDate),
            "YYYY-MM-DD"
        ),

    // === AGGREGATE METRICS ===
    "Orders_CY",
        CALCULATE(
            DISTINCTCOUNT(Sales[transaction_SalesOrderID]),
            Sales[date_Invoice] > SnapshotDate - 365,
            Sales[date_Invoice] <= SnapshotDate
        ),
    "Orders_PY",
        CALCULATE(
            DISTINCTCOUNT(Sales[transaction_SalesOrderID]),
            Sales[date_Invoice] > SnapshotDate - 730,
            Sales[date_Invoice] <= SnapshotDate - 365
        ),
    "Orders_Lifetime",
        CALCULATE(
            DISTINCTCOUNT(Sales[transaction_SalesOrderID]),
            Sales[date_Invoice] <= SnapshotDate
        ),
    "Spend_CY",
        CALCULATE(
            SUM(Sales[amount_Sale]),
            Sales[date_Invoice] > SnapshotDate - 365,
            Sales[date_Invoice] <= SnapshotDate
        ),
    "Spend_PY",
        CALCULATE(
            SUM(Sales[amount_Sale]),
            Sales[date_Invoice] > SnapshotDate - 730,
            Sales[date_Invoice] <= SnapshotDate - 365
        ),
    "Spend_Lifetime",
        CALCULATE(
            SUM(Sales[amount_Sale]),
            Sales[date_Invoice] <= SnapshotDate
        ),
    "Units_CY",
        CALCULATE(
            SUM(Sales[amount_Qty]),
            Sales[date_Invoice] > SnapshotDate - 365,
            Sales[date_Invoice] <= SnapshotDate
        ),
    "Units_PY",
        CALCULATE(
            SUM(Sales[amount_Qty]),
            Sales[date_Invoice] > SnapshotDate - 730,
            Sales[date_Invoice] <= SnapshotDate - 365
        ),
    "Units_Lifetime",
        CALCULATE(
            SUM(Sales[amount_Qty]),
            Sales[date_Invoice] <= SnapshotDate
        ),
    "AOV_CY",
        DIVIDE(
            CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate),
            CALCULATE(DISTINCTCOUNT(Sales[transaction_SalesOrderID]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate),
            0
        ),
    "DaysSinceLast",
        DATEDIFF(
            CALCULATE(MAX(Sales[date_Invoice]), Sales[date_Invoice] <= SnapshotDate),
            SnapshotDate,
            DAY
        ),
    "TenureDays",
        DATEDIFF(Customers[FirstOrdered], SnapshotDate, DAY),

    // === TREND METRICS ===
    "Spend_Trend",
        DIVIDE(
            CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate),
            CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 730, Sales[date_Invoice] <= SnapshotDate - 365),
            BLANK()
        ),
    "Orders_Trend",
        DIVIDE(
            CALCULATE(DISTINCTCOUNT(Sales[transaction_SalesOrderID]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate),
            CALCULATE(DISTINCTCOUNT(Sales[transaction_SalesOrderID]), Sales[date_Invoice] > SnapshotDate - 730, Sales[date_Invoice] <= SnapshotDate - 365),
            BLANK()
        ),
    "Units_Trend",
        DIVIDE(
            CALCULATE(SUM(Sales[amount_Qty]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate),
            CALCULATE(SUM(Sales[amount_Qty]), Sales[date_Invoice] > SnapshotDate - 730, Sales[date_Invoice] <= SnapshotDate - 365),
            BLANK()
        ),

    // === UNIFORMS ===
    "Uniforms_Units_CY",
        CALCULATE(SUM(Sales[amount_Qty]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] IN {"Uniforms", "Student Uniforms", "Specialty Uniforms"}),
    "Uniforms_Units_PY",
        CALCULATE(SUM(Sales[amount_Qty]), Sales[date_Invoice] > SnapshotDate - 730, Sales[date_Invoice] <= SnapshotDate - 365, Product[Department] IN {"Uniforms", "Student Uniforms", "Specialty Uniforms"}),
    "Uniforms_Units_Lifetime",
        CALCULATE(SUM(Sales[amount_Qty]), Sales[date_Invoice] <= SnapshotDate, Product[Department] IN {"Uniforms", "Student Uniforms", "Specialty Uniforms"}),
    "Uniforms_Spend_CY",
        CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] IN {"Uniforms", "Student Uniforms", "Specialty Uniforms"}),
    "Uniforms_Spend_PY",
        CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 730, Sales[date_Invoice] <= SnapshotDate - 365, Product[Department] IN {"Uniforms", "Student Uniforms", "Specialty Uniforms"}),
    "Uniforms_Spend_Lifetime",
        CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] <= SnapshotDate, Product[Department] IN {"Uniforms", "Student Uniforms", "Specialty Uniforms"}),
    "Uniforms_Orders_CY",
        CALCULATE(DISTINCTCOUNT(Sales[transaction_SalesOrderID]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] IN {"Uniforms", "Student Uniforms", "Specialty Uniforms"}),
    "Uniforms_Orders_Lifetime",
        CALCULATE(DISTINCTCOUNT(Sales[transaction_SalesOrderID]), Sales[date_Invoice] <= SnapshotDate, Product[Department] IN {"Uniforms", "Student Uniforms", "Specialty Uniforms"}),
    "Uniforms_DaysSinceLast",
        DATEDIFF(CALCULATE(MAX(Sales[date_Invoice]), Sales[date_Invoice] <= SnapshotDate, Sales[amount_Sale] > 0, Product[Department] IN {"Uniforms", "Student Uniforms", "Specialty Uniforms"}), SnapshotDate, DAY),
    "Uniforms_Pct_of_Total_CY",
        DIVIDE(
            CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] IN {"Uniforms", "Student Uniforms", "Specialty Uniforms"}),
            CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate),
            0
        ),

    // === SPARRING ===
    "Sparring_Units_CY",
        CALCULATE(SUM(Sales[amount_Qty]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] IN {"Sparring", "Protective Accessories"}),
    "Sparring_Units_PY",
        CALCULATE(SUM(Sales[amount_Qty]), Sales[date_Invoice] > SnapshotDate - 730, Sales[date_Invoice] <= SnapshotDate - 365, Product[Department] IN {"Sparring", "Protective Accessories"}),
    "Sparring_Units_Lifetime",
        CALCULATE(SUM(Sales[amount_Qty]), Sales[date_Invoice] <= SnapshotDate, Product[Department] IN {"Sparring", "Protective Accessories"}),
    "Sparring_Spend_CY",
        CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] IN {"Sparring", "Protective Accessories"}),
    "Sparring_Spend_PY",
        CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 730, Sales[date_Invoice] <= SnapshotDate - 365, Product[Department] IN {"Sparring", "Protective Accessories"}),
    "Sparring_Spend_Lifetime",
        CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] <= SnapshotDate, Product[Department] IN {"Sparring", "Protective Accessories"}),
    "Sparring_Orders_CY",
        CALCULATE(DISTINCTCOUNT(Sales[transaction_SalesOrderID]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] IN {"Sparring", "Protective Accessories"}),
    "Sparring_Orders_Lifetime",
        CALCULATE(DISTINCTCOUNT(Sales[transaction_SalesOrderID]), Sales[date_Invoice] <= SnapshotDate, Product[Department] IN {"Sparring", "Protective Accessories"}),
    "Sparring_DaysSinceLast",
        DATEDIFF(CALCULATE(MAX(Sales[date_Invoice]), Sales[date_Invoice] <= SnapshotDate, Sales[amount_Sale] > 0, Product[Department] IN {"Sparring", "Protective Accessories"}), SnapshotDate, DAY),
    "Sparring_Pct_of_Total_CY",
        DIVIDE(
            CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] IN {"Sparring", "Protective Accessories"}),
            CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate),
            0
        ),

    // === BELTS ===
    "Belts_Units_CY",
        CALCULATE(SUM(Sales[amount_Qty]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] = "Belts"),
    "Belts_Units_PY",
        CALCULATE(SUM(Sales[amount_Qty]), Sales[date_Invoice] > SnapshotDate - 730, Sales[date_Invoice] <= SnapshotDate - 365, Product[Department] = "Belts"),
    "Belts_Units_Lifetime",
        CALCULATE(SUM(Sales[amount_Qty]), Sales[date_Invoice] <= SnapshotDate, Product[Department] = "Belts"),
    "Belts_Spend_CY",
        CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] = "Belts"),
    "Belts_Spend_PY",
        CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 730, Sales[date_Invoice] <= SnapshotDate - 365, Product[Department] = "Belts"),
    "Belts_Spend_Lifetime",
        CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] <= SnapshotDate, Product[Department] = "Belts"),
    "Belts_Orders_CY",
        CALCULATE(DISTINCTCOUNT(Sales[transaction_SalesOrderID]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] = "Belts"),
    "Belts_Orders_Lifetime",
        CALCULATE(DISTINCTCOUNT(Sales[transaction_SalesOrderID]), Sales[date_Invoice] <= SnapshotDate, Product[Department] = "Belts"),
    "Belts_DaysSinceLast",
        DATEDIFF(CALCULATE(MAX(Sales[date_Invoice]), Sales[date_Invoice] <= SnapshotDate, Sales[amount_Sale] > 0, Product[Department] = "Belts"), SnapshotDate, DAY),
    "Belts_Pct_of_Total_CY",
        DIVIDE(
            CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] = "Belts"),
            CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate),
            0
        ),

    // === BAGS ===
    "Bags_Units_CY",
        CALCULATE(SUM(Sales[amount_Qty]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] = "Training Bags"),
    "Bags_Units_PY",
        CALCULATE(SUM(Sales[amount_Qty]), Sales[date_Invoice] > SnapshotDate - 730, Sales[date_Invoice] <= SnapshotDate - 365, Product[Department] = "Training Bags"),
    "Bags_Units_Lifetime",
        CALCULATE(SUM(Sales[amount_Qty]), Sales[date_Invoice] <= SnapshotDate, Product[Department] = "Training Bags"),
    "Bags_Spend_CY",
        CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] = "Training Bags"),
    "Bags_Spend_PY",
        CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 730, Sales[date_Invoice] <= SnapshotDate - 365, Product[Department] = "Training Bags"),
    "Bags_Spend_Lifetime",
        CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] <= SnapshotDate, Product[Department] = "Training Bags"),
    "Bags_Orders_CY",
        CALCULATE(DISTINCTCOUNT(Sales[transaction_SalesOrderID]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] = "Training Bags"),
    "Bags_Orders_Lifetime",
        CALCULATE(DISTINCTCOUNT(Sales[transaction_SalesOrderID]), Sales[date_Invoice] <= SnapshotDate, Product[Department] = "Training Bags"),
    "Bags_DaysSinceLast",
        DATEDIFF(CALCULATE(MAX(Sales[date_Invoice]), Sales[date_Invoice] <= SnapshotDate, Sales[amount_Sale] > 0, Product[Department] = "Training Bags"), SnapshotDate, DAY),
    "Bags_Pct_of_Total_CY",
        DIVIDE(
            CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] = "Training Bags"),
            CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate),
            0
        ),

    // === CUSTOMS ===
    "Customs_Units_CY",
        CALCULATE(SUM(Sales[amount_Qty]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[BrandInternalName] IN {"CUSTOMFEE", "CUSTOMPRG", "CUSTOMSTK"}),
    "Customs_Units_PY",
        CALCULATE(SUM(Sales[amount_Qty]), Sales[date_Invoice] > SnapshotDate - 730, Sales[date_Invoice] <= SnapshotDate - 365, Product[BrandInternalName] IN {"CUSTOMFEE", "CUSTOMPRG", "CUSTOMSTK"}),
    "Customs_Units_Lifetime",
        CALCULATE(SUM(Sales[amount_Qty]), Sales[date_Invoice] <= SnapshotDate, Product[BrandInternalName] IN {"CUSTOMFEE", "CUSTOMPRG", "CUSTOMSTK"}),
    "Customs_Spend_CY",
        CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[BrandInternalName] IN {"CUSTOMFEE", "CUSTOMPRG", "CUSTOMSTK"}),
    "Customs_Spend_PY",
        CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 730, Sales[date_Invoice] <= SnapshotDate - 365, Product[BrandInternalName] IN {"CUSTOMFEE", "CUSTOMPRG", "CUSTOMSTK"}),
    "Customs_Spend_Lifetime",
        CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] <= SnapshotDate, Product[BrandInternalName] IN {"CUSTOMFEE", "CUSTOMPRG", "CUSTOMSTK"}),
    "Customs_Orders_CY",
        CALCULATE(DISTINCTCOUNT(Sales[transaction_SalesOrderID]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[BrandInternalName] IN {"CUSTOMFEE", "CUSTOMPRG", "CUSTOMSTK"}),
    "Customs_Orders_Lifetime",
        CALCULATE(DISTINCTCOUNT(Sales[transaction_SalesOrderID]), Sales[date_Invoice] <= SnapshotDate, Product[BrandInternalName] IN {"CUSTOMFEE", "CUSTOMPRG", "CUSTOMSTK"}),
    "Customs_DaysSinceLast",
        DATEDIFF(CALCULATE(MAX(Sales[date_Invoice]), Sales[date_Invoice] <= SnapshotDate, Sales[amount_Sale] > 0, Product[BrandInternalName] IN {"CUSTOMFEE", "CUSTOMPRG", "CUSTOMSTK"}), SnapshotDate, DAY),
    "Customs_Pct_of_Total_CY",
        DIVIDE(
            CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[BrandInternalName] IN {"CUSTOMFEE", "CUSTOMPRG", "CUSTOMSTK"}),
            CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate),
            0
        ),

    // === BREADTH METRICS ===
    "CUBS_Categories_Active_CY",
        (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] IN {"Uniforms", "Student Uniforms", "Specialty Uniforms"}) > 0, 1, 0))
        + (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] IN {"Sparring", "Protective Accessories"}) > 0, 1, 0))
        + (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] = "Belts") > 0, 1, 0))
        + (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] = "Training Bags") > 0, 1, 0))
        + (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[BrandInternalName] IN {"CUSTOMFEE", "CUSTOMPRG", "CUSTOMSTK"}) > 0, 1, 0)),

    "CUBS_Categories_Active_PY",
        (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 730, Sales[date_Invoice] <= SnapshotDate - 365, Product[Department] IN {"Uniforms", "Student Uniforms", "Specialty Uniforms"}) > 0, 1, 0))
        + (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 730, Sales[date_Invoice] <= SnapshotDate - 365, Product[Department] IN {"Sparring", "Protective Accessories"}) > 0, 1, 0))
        + (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 730, Sales[date_Invoice] <= SnapshotDate - 365, Product[Department] = "Belts") > 0, 1, 0))
        + (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 730, Sales[date_Invoice] <= SnapshotDate - 365, Product[Department] = "Training Bags") > 0, 1, 0))
        + (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 730, Sales[date_Invoice] <= SnapshotDate - 365, Product[BrandInternalName] IN {"CUSTOMFEE", "CUSTOMPRG", "CUSTOMSTK"}) > 0, 1, 0)),

    "CUBS_Categories_Ever",
        (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] <= SnapshotDate, Product[Department] IN {"Uniforms", "Student Uniforms", "Specialty Uniforms"}) > 0, 1, 0))
        + (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] <= SnapshotDate, Product[Department] IN {"Sparring", "Protective Accessories"}) > 0, 1, 0))
        + (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] <= SnapshotDate, Product[Department] = "Belts") > 0, 1, 0))
        + (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] <= SnapshotDate, Product[Department] = "Training Bags") > 0, 1, 0))
        + (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] <= SnapshotDate, Product[BrandInternalName] IN {"CUSTOMFEE", "CUSTOMPRG", "CUSTOMSTK"}) > 0, 1, 0)),

    "CUBS_Categories_Trend",
        (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] IN {"Uniforms", "Student Uniforms", "Specialty Uniforms"}) > 0, 1, 0))
        + (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] IN {"Sparring", "Protective Accessories"}) > 0, 1, 0))
        + (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] = "Belts") > 0, 1, 0))
        + (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[Department] = "Training Bags") > 0, 1, 0))
        + (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 365, Sales[date_Invoice] <= SnapshotDate, Product[BrandInternalName] IN {"CUSTOMFEE", "CUSTOMPRG", "CUSTOMSTK"}) > 0, 1, 0))
        - (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 730, Sales[date_Invoice] <= SnapshotDate - 365, Product[Department] IN {"Uniforms", "Student Uniforms", "Specialty Uniforms"}) > 0, 1, 0))
        - (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 730, Sales[date_Invoice] <= SnapshotDate - 365, Product[Department] IN {"Sparring", "Protective Accessories"}) > 0, 1, 0))
        - (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 730, Sales[date_Invoice] <= SnapshotDate - 365, Product[Department] = "Belts") > 0, 1, 0))
        - (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 730, Sales[date_Invoice] <= SnapshotDate - 365, Product[Department] = "Training Bags") > 0, 1, 0))
        - (IF(CALCULATE(SUM(Sales[amount_Sale]), Sales[date_Invoice] > SnapshotDate - 730, Sales[date_Invoice] <= SnapshotDate - 365, Product[BrandInternalName] IN {"CUSTOMFEE", "CUSTOMPRG", "CUSTOMSTK"}) > 0, 1, 0))
)

ORDER BY Customers[account_Order]
